// Liste EXACTE et COMPLÈTE des engins CML importés du fichier Excel officiel
// Chaque engin est reproduit textuellement avec son ID_ENGIN, TYPE, MARQUE et MODELE
export const ENGINES_LIST = [
  // ===== CHARGEUSES (CH0004 → CH0042) =====
  { code: "CH0004", type: "Minier Lourd", marque: "Chargeuse Komatsu", categorie: "Chargeuse", wa: "WA 470-82664", department: "Exploitation Minière", normalConsumption: 45.0, unit: "L/H", tankCapacity: 700 },
  { code: "CH0005", type: "Minier Lourd", marque: "Chargeuse hitachi", categorie: "Chargeuse", wa: "Zw 310-70373", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0006", type: "Minier Lourd", marque: "Chargeuse hitachi", categorie: "Chargeuse", wa: "Zw 310-70359", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0007", type: "Minier Lourd", marque: "Chargeuse hitachi", categorie: "Chargeuse", wa: "Zw 310-70385", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0010", type: "Minier Lourd", marque: "Chargeuse hitachi", categorie: "Chargeuse", wa: "Zw 310-70419", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0011", type: "Minier Lourd", marque: "Chargeuse Komatsu", categorie: "Chargeuse", wa: "WA 500-60237", department: "Exploitation Minière", normalConsumption: 48.0, unit: "L/H", tankCapacity: 720 },
  { code: "CH0012", type: "Minier Lourd", marque: "Chargeuse Komatsu", categorie: "Chargeuse", wa: "WA 500-60236", department: "Exploitation Minière", normalConsumption: 48.0, unit: "L/H", tankCapacity: 720 },
  { code: "CH0014", type: "Minier Lourd", marque: "Chargeuse Komatsu", categorie: "Chargeuse", wa: "WA 470-82816", department: "Exploitation Minière", normalConsumption: 45.0, unit: "L/H", tankCapacity: 700 },
  { code: "CH0015", type: "Minier Lourd", marque: "Chargeuse hitachi", categorie: "Chargeuse", wa: "Zw 310-70436", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0030", type: "Minier Lourd", marque: "Chargeuse", categorie: "Chargeuse", wa: "260HH00004320 / L260H -HK00013394", department: "Exploitation Minière", normalConsumption: 35.0, unit: "L/H", tankCapacity: 500 },
  { code: "CH0031", type: "Minier Lourd", marque: "Chargeuse", categorie: "Chargeuse", wa: "180HK00013394 / L180H-HH00004320", department: "Exploitation Minière", normalConsumption: 30.0, unit: "L/H", tankCapacity: 450 },
  { code: "CH0032", type: "Minier Lourd", marque: "Chargeuse", categorie: "Chargeuse", wa: "180H / 180HC00013437 -HE00013437", department: "Exploitation Minière", normalConsumption: 30.0, unit: "L/H", tankCapacity: 450 },
  { code: "CH0033", type: "Minier Lourd", marque: "Chargeuse", categorie: "Chargeuse", wa: "180H / 180HC00013438-HC00013438", department: "Exploitation Minière", normalConsumption: 30.0, unit: "L/H", tankCapacity: 450 },
  { code: "CH0034", type: "Minier Lourd", marque: "Chargeuse XCMG", categorie: "Chargeuse", wa: "(ZL50GN)-XUG0050LPCB15310", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },
  { code: "CH0035", type: "Minier Lourd", marque: "Chargeuse XCMG", categorie: "Chargeuse", wa: "(ZL50GN)-XUG0050GPPC15315", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },
  { code: "CH0036", type: "Minier Lourd", marque: "Chargeuse XCMG", categorie: "Chargeuse", wa: "(ZL50GN)-XUG0050GPPC15317", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },
  { code: "CH0037", type: "Minier Lourd", marque: "XCMG", categorie: "Chargeuse", wa: "LW 500 FN -XUG0500FJNCE21725", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },
  { code: "CH0038", type: "Minier Lourd", marque: "XCMG", categorie: "Chargeuse", wa: "LW 500 FN -XUG0500FKNCE21724", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },
  { code: "CH0039", type: "Minier Lourd", marque: "SHAN TUI", categorie: "Chargeuse", wa: "SL50WN-86SL50LENMN014507", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0040", type: "Minier Lourd", marque: "SHAN TUI", categorie: "Chargeuse", wa: "SL50WN-86SL50LENMN014506", department: "Exploitation Minière", normalConsumption: 40.0, unit: "L/H", tankCapacity: 600 },
  { code: "CH0041", type: "Minier Lourd", marque: "XCMG", categorie: "Chargeuse", wa: "ZL50GN-XUG0050GEMCB08260", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },
  { code: "CH0042", type: "Minier Lourd", marque: "XCMG", categorie: "Chargeuse", wa: "ZL50GN-XUG0050GCMCB08261", department: "Exploitation Minière", normalConsumption: 42.0, unit: "L/H", tankCapacity: 650 },

  // ===== CAMIONS (CM0001 → CM0054) =====
  { code: "CM0001", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2159 HE01-2159 HE01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0002", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2160 HE01-2160 HE01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0003", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2161 HE01-2161 HE01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0004", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2162 HE01-2162 HE01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0006", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2835 HE01-2835 HE01", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "CM0007", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2838 HE01-2838 HE01", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "CM0009", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2845 HE01-2845 HE01", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "CM0010", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 2848 HE01-2848 HE01", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "CM0011", type: "Minier Lourd", marque: "FOTON", categorie: "Camion", wa: "AA-802-JT01", department: "Logistique", normalConsumption: 35.0, unit: "L/100km", tankCapacity: 300 },
  { code: "CM0012", type: "Minier Lourd", marque: "ISUZU", categorie: "Camion", wa: "ISUZU-3441 LR01", department: "Logistique", normalConsumption: 30.0, unit: "L/100km", tankCapacity: 250 },
  { code: "CM0013", type: "Minier Lourd", marque: "ISUZU", categorie: "Camion", wa: "ISUZU-3217 LR01", department: "Logistique", normalConsumption: 30.0, unit: "L/100km", tankCapacity: 250 },
  { code: "CM0014", type: "Minier Lourd", marque: "MAN", categorie: "Camion", wa: "MAN-AA-953-LF01", department: "Logistique", normalConsumption: 40.0, unit: "L/100km", tankCapacity: 400 },
  { code: "CM0016", type: "Minier Lourd", marque: "HOWO", categorie: "Camion", wa: "Camion-citerne à gas-oil 9023HR01-9023 HR01", department: "Station", normalConsumption: 45.0, unit: "L/100km", tankCapacity: 500 },
  { code: "CM0017", type: "Minier Lourd", marque: "SINOTRUCK", categorie: "Camion", wa: "Tracteur du porte charre 4789 HS01-4789 HS01", department: "Logistique", normalConsumption: 48.0, unit: "L/100km", tankCapacity: 600 },
  { code: "CM0018", type: "Minier Lourd", marque: "SINOTRUCK", categorie: "Camion", wa: "SINOTRUK-8191 HT01", department: "Logistique", normalConsumption: 45.0, unit: "L/100km", tankCapacity: 500 },
  { code: "CM0020", type: "Minier Lourd", marque: "ISUZU", categorie: "Camion", wa: "Car du personnel ISUZU 759 JP01-759 JP01", department: "Ressource Humaine", normalConsumption: 25.0, unit: "L/100km", tankCapacity: 200 },
  { code: "CM0021", type: "Minier Lourd", marque: "ISUZU", categorie: "Camion", wa: "Car du personnel ISUZU 9859 JL01-9859 JL01", department: "Ressource Humaine", normalConsumption: 25.0, unit: "L/100km", tankCapacity: 200 },
  { code: "CM0022", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 8826 JK01-8826 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0024", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 8828 JK01-8828 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0025", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 8830 JK01-8830 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0026", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 126 JK01-126 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0027", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 129JK01-129 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0028", type: "Minier Lourd", marque: "HYUNDAI", categorie: "Camion", wa: "Ambulance Hyundai 7289 JT01-7289 JT01", department: "Sécurité", normalConsumption: 22.0, unit: "L/100km", tankCapacity: 150 },
  { code: "CM0029", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 8829 JK01-8829 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0030", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 134 JK01-134 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0031", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion benne 8827 JK01-8827 JK01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 800 },
  { code: "CM0032", type: "Minier Lourd", marque: "XCMG", categorie: "Camion", wa: "Citerne à eau XCMG 1611 JY01-1611 JY01", department: "Environnement & Hygiène", normalConsumption: 40.0, unit: "L/100km", tankCapacity: 400 },
  { code: "CM0033", type: "Minier Lourd", marque: "sinotruk", categorie: "Camion", wa: "Citerne à gas-oil (sinotruk 290) 1610 JY01-1610 JY01", department: "Station", normalConsumption: 45.0, unit: "L/100km", tankCapacity: 500 },
  { code: "CM0034", type: "Minier Lourd", marque: "ISUZU", categorie: "Camion", wa: "Car ISUZU 16483 WW CI 01-3441 LR01", department: "Ressource Humaine", normalConsumption: 25.0, unit: "L/100km", tankCapacity: 200 },
  { code: "CM0035", type: "Minier Lourd", marque: "ISUZU", categorie: "Camion", wa: "Car ISUZU 17932 WW CI 01-3217 LR01", department: "Ressource Humaine", normalConsumption: 25.0, unit: "L/100km", tankCapacity: 200 },
  { code: "CM0036", type: "Minier Lourd", marque: "SINOTRUCK", categorie: "Camion", wa: "Camion citerne a eau SINOTRUCK-AA-148-FL01", department: "Environnement & Hygiène", normalConsumption: 42.0, unit: "L/100km", tankCapacity: 450 },
  { code: "CM0037", type: "Minier Lourd", marque: "SINOTRUCK", categorie: "Camion", wa: "Camion citerne a eau SINOTRUCK-AA-147-FL01", department: "Environnement & Hygiène", normalConsumption: 42.0, unit: "L/100km", tankCapacity: 450 },
  { code: "CM0038", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "Camion entretien -AA-802-JT01", department: "Maintenance", normalConsumption: 30.0, unit: "L/100km", tankCapacity: 300 },
  { code: "CM0039", type: "Minier Lourd", marque: "GRUE", categorie: "Camion", wa: "Camion GRUE -AA-953-LF01", department: "Maintenance", normalConsumption: 35.0, unit: "L/H", tankCapacity: 400 },
  { code: "CM0040", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-370-KV01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0041", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-029-KV01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0042", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-841-KT01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0043", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-784-KT01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0044", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-786-KT01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0045", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-921-KS01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0046", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-851-KT01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0047", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-023-KV01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0048", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-027-LG01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0049", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-051-LG01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0050", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-106-LH01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0051", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-257-KY01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0052", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-367-KV01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0053", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-391-KV01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },
  { code: "CM0054", type: "Minier Lourd", marque: "Camion", categorie: "Camion", wa: "CAMION TRANSPORT MINERAIE-AA-611-KS01", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/100km", tankCapacity: 700 },

  // ===== CRIBLES (CR0004 → CR0012) =====
  { code: "CR0004", type: "Minier Lourd", marque: "Crible", categorie: "Crible", wa: "CRIBLE SANDVICK QA441 -10033", department: "Traitement (Usine 1)", normalConsumption: 32.0, unit: "L/H", tankCapacity: 450 },
  { code: "CR0005", type: "Minier Lourd", marque: "Crible", categorie: "Crible", wa: "CRIBLE SANDVICK QA441 -10054", department: "Traitement (Usine 1)", normalConsumption: 32.0, unit: "L/H", tankCapacity: 450 },
  { code: "CR0006", type: "Minier Lourd", marque: "Crible", categorie: "Crible", wa: "CRIBLE SANDVICK QA441-10053", department: "Traitement (Usine 1)", normalConsumption: 32.0, unit: "L/H", tankCapacity: 450 },
  { code: "CR0007", type: "Minier Lourd", marque: "METSO", categorie: "Crible", wa: "CRIBLE METSO LOKOTRACK ST3.8 -181349", department: "Traitement (Usine 2)", normalConsumption: 34.0, unit: "L/H", tankCapacity: 470 },
  { code: "CR0008", type: "Minier Lourd", marque: "METSO", categorie: "Crible", wa: "CRIBLE METSO LOKOTRACK ST3.8 -181350", department: "Traitement (Usine 2)", normalConsumption: 34.0, unit: "L/H", tankCapacity: 470 },
  { code: "CR0009", type: "Minier Lourd", marque: "TERREX", categorie: "Crible", wa: "CRIBLE TERREX À EAU - TRX00124CDGN78496", department: "Traitement (Usine 1)", normalConsumption: 30.0, unit: "L/H", tankCapacity: 400 },
  { code: "CR0010", type: "Minier Lourd", marque: "TERREX", categorie: "Crible", wa: "CRIBLE TERREX À EAU - TRX00124JDGN68310", department: "Traitement (Usine 1)", normalConsumption: 30.0, unit: "L/H", tankCapacity: 400 },
  { code: "CR0011", type: "Minier Lourd", marque: "Crible", categorie: "Crible", wa: "Crible KLEEMAN-11", department: "Traitement (Usine 2)", normalConsumption: 33.0, unit: "L/H", tankCapacity: 450 },
  { code: "CR0012", type: "Minier Lourd", marque: "Crible", categorie: "Crible", wa: "Crible KLEEMAN-12", department: "Traitement (Usine 2)", normalConsumption: 33.0, unit: "L/H", tankCapacity: 450 },

  // ===== GROUPES ÉLECTROGÈNES (GE0004 → GE0019) =====
  { code: "GE0004", type: "Minier Lourd", marque: "VOLVO", categorie: "Groupe Electrogène", wa: "VOLVO 650 KVA-2016114471", department: "Traitement (Usine 1)", normalConsumption: 45.0, unit: "L/H", tankCapacity: 1000 },
  { code: "GE0005", type: "Minier Lourd", marque: "VOLVO", categorie: "Groupe Electrogène", wa: "VOLVO 650 KVA-2016142392", department: "Traitement (Usine 1)", normalConsumption: 45.0, unit: "L/H", tankCapacity: 1000 },
  { code: "GE0006", type: "Minier Lourd", marque: "VOLVO", categorie: "Groupe Electrogène", wa: "VOLVO 650 KVA-2016135509", department: "Traitement (Usine 2)", normalConsumption: 45.0, unit: "L/H", tankCapacity: 1000 },
  { code: "GE0007", type: "Minier Lourd", marque: "PERKINS", categorie: "Groupe Electrogène", wa: "PERKINS-DGDF6002U12680C", department: "Maintenance", normalConsumption: 40.0, unit: "L/H", tankCapacity: 900 },
  { code: "GE0009", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS 200 KVA-MH201201080", department: "Traitement (Usine 1)", normalConsumption: 25.0, unit: "L/H", tankCapacity: 600 },
  { code: "GE0010", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS 200 KVA-201201081", department: "Traitement (Usine 1)", normalConsumption: 25.0, unit: "L/H", tankCapacity: 600 },
  { code: "GE0011", type: "Minier Lourd", marque: "Groupe Electrogène", categorie: "Groupe Electrogène", wa: "FG15000SE3/ ATS 12KVA-SG1982024070529", department: "Administration", normalConsumption: 10.0, unit: "L/H", tankCapacity: 200 },
  { code: "GE0012", type: "Minier Lourd", marque: "Groupe Electrogène", categorie: "Groupe Electrogène", wa: "FG15000SE3/ ATS 12KVA-SG1982024070541", department: "Administration", normalConsumption: 10.0, unit: "L/H", tankCapacity: 200 },
  { code: "GE0013", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS 250 KVA-41321178", department: "Traitement (Usine 2)", normalConsumption: 30.0, unit: "L/H", tankCapacity: 700 },
  { code: "GE0014", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS 100KVA-1703381", department: "Magasin", normalConsumption: 15.0, unit: "L/H", tankCapacity: 300 },
  { code: "GE0015", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS-", department: "Maintenance", normalConsumption: 20.0, unit: "L/H", tankCapacity: 400 },
  { code: "GE0016", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS -41322053", department: "Traitement (Usine 1)", normalConsumption: 30.0, unit: "L/H", tankCapacity: 700 },
  { code: "GE0017", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS -41322056", department: "Traitement (Usine 1)", normalConsumption: 30.0, unit: "L/H", tankCapacity: 700 },
  { code: "GE0018", type: "Minier Lourd", marque: "CUMMINS", categorie: "Groupe Electrogène", wa: "CUMMINS -41322051", department: "Traitement (Usine 2)", normalConsumption: 30.0, unit: "L/H", tankCapacity: 700 },
  { code: "GE0019", type: "Minier Lourd", marque: "PERKINS", categorie: "Groupe Electrogène", wa: "PERKINS 600KVA usine 1-WP13D490E310", department: "Traitement (Usine 1)", normalConsumption: 42.0, unit: "L/H", tankCapacity: 950 },

  // ===== NIVELEUSE (GR0001) =====
  { code: "GR0001", type: "Minier Lourd", marque: "Niveleuse", categorie: "Niveleuse", wa: "GRADER GR215-", department: "Logistique", normalConsumption: 28.0, unit: "L/H", tankCapacity: 490 },

  // ===== PELLES HYDRAULIQUES (PL0001 → PL0017) =====
  { code: "PL0001", type: "Minier Lourd", marque: "HITACHI", categorie: "Pelle Hydraulique", wa: "PELLE HITACHI 350-42311", department: "Exploitation Minière", normalConsumption: 50.0, unit: "L/H", tankCapacity: 800 },
  { code: "PL0002", type: "Minier Lourd", marque: "HITACHI", categorie: "Pelle Hydraulique", wa: "PELLE HITACHI 470-50930", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "PL0003", type: "Minier Lourd", marque: "HITACHI", categorie: "Pelle Hydraulique", wa: "PELLE HITACHI 470-51399", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "PL0004", type: "Minier Lourd", marque: "HITACHI", categorie: "Pelle Hydraulique", wa: "PELLE HITACHI 470-51400", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "PL0005", type: "Minier Lourd", marque: "Komatsu", categorie: "Pelle Hydraulique", wa: "pelle Komatsu 850-70284", department: "Exploitation Minière", normalConsumption: 65.0, unit: "L/H", tankCapacity: 950 },
  { code: "PL0007", type: "Minier Lourd", marque: "HITACHI", categorie: "Pelle Hydraulique", wa: "PELLE HITACHI 470-51599", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "PL0008", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370C-XUG03703CGKA01866", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0009", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370C-XUG03703KHKA01937", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0010", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370C-XUG03703AHKA01958", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0011", type: "Minier Lourd", marque: "HITACHI", categorie: "Pelle Hydraulique", wa: "PELLE HITACHI 470-", department: "Exploitation Minière", normalConsumption: 60.0, unit: "L/H", tankCapacity: 900 },
  { code: "PL0012", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370CA-XUGE3703LPKA04283", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0013", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370CA-XUGE3703VPKA04331", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0014", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370CA-XUGE3703CPKA04112", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0015", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370CA-XUGE3703ENKA03599", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0016", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370CA-XUGE3703CNKA03613", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },
  { code: "PL0017", type: "Minier Lourd", marque: "Pelle Hydraulique", categorie: "Pelle Hydraulique", wa: "PELLE XE370CA-XUGB3803CMKA02453", department: "Exploitation Minière", normalConsumption: 55.0, unit: "L/H", tankCapacity: 850 },

  // ===== VÉHICULES LÉGERS DIRECTION (VD0001 → VD0015) =====
  { code: "VD0001", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota fortuner-6134 JJ01", department: "Direction générale", normalConsumption: 11.5, unit: "L/100km", tankCapacity: 80 },
  { code: "VD0002", type: "Véhicule Léger (LV)", marque: "FORD", categorie: "LV", wa: "FORD EDGE-232JK01", department: "Direction générale", normalConsumption: 12.0, unit: "L/100km", tankCapacity: 85 },
  { code: "VD0003", type: "Véhicule Léger (LV)", marque: "ISUZU", categorie: "LV", wa: "Isuzu mu-x -1131 KV01", department: "Direction générale", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VD0004", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA PRADO-4330KP01", department: "Direction générale", normalConsumption: 12.5, unit: "L/100km", tankCapacity: 90 },
  { code: "VD0005", type: "Véhicule Léger (LV)", marque: "KIA", categorie: "LV", wa: "KIA SPORTAGE-4962LL01", department: "Direction générale", normalConsumption: 10.5, unit: "L/100km", tankCapacity: 70 },
  { code: "VD0006", type: "Véhicule Léger (LV)", marque: "NISSAN", categorie: "LV", wa: "NISSAN TERRA-1097WWCI01 / AA-890-HP", department: "Direction générale", normalConsumption: 11.5, unit: "L/100km", tankCapacity: 80 },
  { code: "VD0007", type: "Véhicule Léger (LV)", marque: "NISSAN", categorie: "LV", wa: "NISSAN PATROL V8-AA-295-AK", department: "Direction générale", normalConsumption: 14.0, unit: "L/100km", tankCapacity: 95 },
  { code: "VD0008", type: "Véhicule Léger (LV)", marque: "MITSUBISHI", categorie: "LV", wa: "MITSUBISHI PAJERO-AA-567-EP", department: "Direction Technique", normalConsumption: 12.5, unit: "L/100km", tankCapacity: 88 },
  { code: "VD0009", type: "Véhicule Léger (LV)", marque: "MITSUBISHI", categorie: "LV", wa: "MITSUBISHI L200-AA-535-EQ", department: "Direction Technique", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VD0010", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-443-JN", department: "Direction Technique", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VD0011", type: "Véhicule Léger (LV)", marque: "MERCEDES", categorie: "LV", wa: "MERCEDES E 200-AA-409-RL01", department: "Direction générale", normalConsumption: 9.5, unit: "L/100km", tankCapacity: 65 },
  { code: "VD0012", type: "Véhicule Léger (LV)", marque: "NISSAN", categorie: "LV", wa: "NISSAN PATROL -AA-834-RK01", department: "Direction générale", normalConsumption: 13.5, unit: "L/100km", tankCapacity: 90 },
  { code: "VD0013", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA FORTUNER-2009 KC01", department: "Direction Technique", normalConsumption: 11.5, unit: "L/100km", tankCapacity: 80 },
  { code: "VD0014", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA PRADO-2401KL01", department: "Direction générale", normalConsumption: 12.5, unit: "L/100km", tankCapacity: 90 },
  { code: "VD0015", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-955-JS", department: "Direction Technique", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },

  // ===== VÉHICULES LÉGERS FONCTION (VF0001 → VF0017) =====
  { code: "VF0001", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA HILUX-9360 HR01", department: "Maintenance", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0002", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-9361 HR01", department: "Maintenance", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0003", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-6277 JJ01", department: "Géologie", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0004", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-196 JL01", department: "Géologie", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0005", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-197 JL01", department: "Géologie", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0006", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-377 JL01", department: "Laboratoire", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0007", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-7655 JL01", department: "Laboratoire", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0008", type: "Véhicule Léger (LV)", marque: "MAZDA", categorie: "LV", wa: "MAZDA -1539JK01", department: "Environnement & Hygiène", normalConsumption: 10.0, unit: "L/100km", tankCapacity: 70 },
  { code: "VF0009", type: "Véhicule Léger (LV)", marque: "KIA", categorie: "LV", wa: "KIA PEGAS-269 LE01", department: "Administration", normalConsumption: 8.5, unit: "L/100km", tankCapacity: 60 },
  { code: "VF0010", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA HILUX-AA-131-JP01", department: "Maintenance", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0011", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA RAV 4-327LL01", department: "Administration", normalConsumption: 9.5, unit: "L/100km", tankCapacity: 65 },
  { code: "VF0012", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-142-BY", department: "Maintenance", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0013", type: "Véhicule Léger (LV)", marque: "MITSUBISHI", categorie: "LV", wa: "MITSUBISHI L200-85009WWCI01", department: "Maintenance", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0014", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux -25620WWCI01 /AA-599-TY-01", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VF0015", type: "Véhicule Léger (LV)", marque: "YUTONG", categorie: "LV", wa: "YUTONG-AA-494-TK-01", department: "Ressource Humaine", normalConsumption: 22.0, unit: "L/100km", tankCapacity: 200 },
  { code: "VF0016", type: "Véhicule Léger (LV)", marque: "YUTONG", categorie: "LV", wa: "YUTONG-AA-536-TY-01", department: "Ressource Humaine", normalConsumption: 22.0, unit: "L/100km", tankCapacity: 200 },
  { code: "VF0017", type: "Véhicule Léger (LV)", marque: "MAZDA", categorie: "LV", wa: "MAZDA BT 50 -2671JK01", department: "Moyen généraux", normalConsumption: 10.0, unit: "L/100km", tankCapacity: 75 },

  // ===== VÉHICULES LÉGERS SÉCURITÉ / STAFF (VS0001 → VS0013) =====
  { code: "VS0001", type: "Véhicule Léger (LV)", marque: "MAZDA", categorie: "LV", wa: "MAZDA BT 50 -923JK01", department: "Moyen généraux", normalConsumption: 10.0, unit: "L/100km", tankCapacity: 75 },
  { code: "VS0002", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA HILUX-AA -203-BK", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0003", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-136-BY", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0004", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-137-BY", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0005", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-139-BY", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0006", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-130-JP", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0007", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-25618WWCI01 /AA-582 TY-01", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0008", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-25619WWCI01 / AA-571-TY-01", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0009", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-497-TY", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0010", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA HILUX-AA-582-TY-01", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0011", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "TOYOTA HILUX-AA-571-TY-01", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0012", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-240-JR", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 },
  { code: "VS0013", type: "Véhicule Léger (LV)", marque: "TOYOTA", categorie: "LV", wa: "Toyota hilux-AA-156-JP", department: "Sécurité", normalConsumption: 11.0, unit: "L/100km", tankCapacity: 80 }
];

// Liste officielle des services CML pour le formulaire de ravitaillement
export const SERVICES_CML = [
  "Exploitation Minière",
  "Traitement (Usine 1)",
  "Traitement (Usine 2)",
  "Laboratoire",
  "Géologie",
  "Maintenance",
  "Logistique",
  "Administration",
  "Station",
  "Magasin",
  "Service Achat",
  "Moyen généraux",
  "Direction générale",
  "Environnement & Hygiène",
  "Sécurité",
  "Ressource Humaine",
  "Direction Technique"
];
